name: Delete Review App

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Website Bucket
        uses: danburtenshaw/s3-website-pr-action@v2
        with:
          bucket-prefix: "fopi-review-app"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
